# Generated by Django 5.2.8 on 2025-11-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertype_customuser_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='profile_images/'),
        ),
    ]
