# Generated by Django 5.2.8 on 2025-11-21 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bgm', 'BGM'), ('sfx', 'SFX'), ('music', 'Música'), ('ost', 'OST'), ('compilation', 'Compilaciones')], max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono o emoji', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'flac'])])),
                ('cover_image', models.ImageField(blank=True, help_text='Imagen de portada del audio', null=True, upload_to='audio_covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Precio en USD', max_digits=10)),
                ('duration', models.IntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('downloads', models.PositiveIntegerField(default=0, help_text='Cantidad de descargas')),
                ('is_active', models.BooleanField(default=True, help_text='Si el audio está disponible para venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type__name': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
                ('audio_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='core.audiotype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
